# Deep learning
# Tuần 2: numpy, pandas, matlotpit
# Numpy

In [1]:
# Numpy là thư viện kiểu list
# Vì
# Numpy nhanh
# Có nhiêu hàm tích hợp để sử dụng cho AI

# Đẻ sử dụng numpy thì: pip install numpy
import numpy as np


In [2]:
# Thử tạo 1 list
python_list = [1,2,3]
# Chuyển đổi danh sách trên thành numpy list
numpy_list = np.array(python_list)
type(numpy_list)

numpy.ndarray

In [3]:
# List trong python có thể hỗ trợ nhiều loại dữ liệu khác nhau trong list
my_list = [1, "Chào",True, 2.0]

In [4]:
my_list = [1, 2, 3, 4, 5]
np_list = np.array(my_list)
np_list


array([1, 2, 3, 4, 5])

In [5]:
# Chuyển đổi kiểu dữ liệu thì sao?
np_list_int = np_list.astype(int)
np_list_int


array([1, 2, 3, 4, 5])

In [6]:
# Accessing và indexing
x= np.array([1,2,3,4,5,6,7,8,]) # x= np.array([range(1,9)])



In [7]:
# Lấy số 4
x[3]


np.int64(4)

In [8]:
# Lấy nhiều hơn 1 phần tử
# Công thức: [start:and:step]
# Lấy 1 2 3
x[0:3]

array([1, 2, 3])

In [9]:
# Lấy từ 3 đến 8 theo 3 cách
#C1
x[2:8]
x[2:8:1]

array([3, 4, 5, 6, 7, 8])

In [10]:
#C2
x[2:]


array([3, 4, 5, 6, 7, 8])

In [11]:
#C3 không đúng
x[2:-1]

array([3, 4, 5, 6, 7])

In [12]:
# Lấy số 3 và 5
x[2], x[4]

(np.int64(3), np.int64(5))

In [13]:
# Đặt danh sách các index muốn truy cập 
x[[2,4]]

array([3, 5])

In [14]:
data = [[1,2],[3,4],[5,6]]
np_list=np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
# Lấy số 2
np_list[0,1]

np.int64(2)

In [16]:
# Lấy số 6
np_list[2,1]

np.int64(6)

In [17]:
# Lấy [3,4],[5,6]
# C1
np_list[1:, :]

array([[3, 4],
       [5, 6]])

In [18]:
# C2
np_list[[1, 2], :]

array([[3, 4],
       [5, 6]])

In [19]:
# C3
np_list[-2:,]

array([[3, 4],
       [5, 6]])

In [20]:
# Lấy 1 3 5
np_list[:,0]

array([1, 3, 5])

In [21]:
# Lấy 1 và 5 theo 2 cách
# C1
np_list[::2,0]
# C2
np_list[[0,2],0]

array([1, 5])

In [22]:
import numpy as np

x = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

np_list = np.array(x)
np_list


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
# Lấy 2 6 10 14
np_list[:, 1:2]

array([[ 2],
       [ 6],
       [10],
       [14]])

In [24]:
# Láy 7 và 11
np_list[[1, 2], 2]

array([ 7, 11])

In [25]:
# Lấy 4 7 10
np_list[[0, 1, 2], [3, 2, 1]]


array([ 4,  7, 10])

In [26]:
# Lấy 16 15 14 13
#C1
np_list[3, ::-1]

array([16, 15, 14, 13])

In [27]:
#C2
np_list[-1, ::-1]

array([16, 15, 14, 13])

# BTVN 1
Cho ma trận = [[99,99,99],
                
                [99,99,99],
                
                [99,99,99]]
Hãy tưởng tượng ô 99 trống 

Giả sử 1 là x

Giả sử 0 là o

Lấy đầu vào từ phía x và phía o luân phiên

Nếu đầu vào từ phía x là (0,0)

Ma trận sẽ trở thành

[[99,99,99],

[99,99,99],

[99,99,99]]

Nếu đầu vào từ phía o cũng là (0,0)

Thông báo họ nhập lại

Nếu không thì điền vào ma trận

Thử thách: Nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi.

In [ ]:
import numpy as np

# Khởi tạo bàn cờ
board = np.full((3,3), 99)

def check_win(board, player):
    # Kiểm tra hàng
    for i in range(3):
        if np.all(board[i, :] == player):
            return True
    
    # Kiểm tra cột
    for i in range(3):
        if np.all(board[:, i] == player):
            return True
    
    # Kiểm tra đường chéo
    if np.all(np.diag(board) == player):
        return True
    if np.all(np.diag(np.fliplr(board)) == player):
        return True
    
    return False

player = 1  # X đi trước

while True:
    print(board)
    row = int(input("Nhập hàng (0-2): "))
    col = int(input("Nhập cột (0-2): "))

    # Kiểm tra ô trống
    if board[row, col] != 99:
        print("Ô đã được đánh, nhập lại!")
        continue

    board[row, col] = player

    # Kiểm tra thắng
    if check_win(board, player):
        print(board)
        print("Người chơi", "X" if player == 1 else "O", "thắng!")
        break

    # Đổi lượt
    player = 0 if player == 1 else 1


[[99 99 99]
 [99 99 99]
 [99 99 99]]


# BTVN 2
y= [
    [1,2,3],

    [4,5,6],

    [7,8,9]
]

Lấy 4,5,6

Lấy 2,5,

Lấy 3,4

Lấy 9.6.3


In [2]:
import numpy as np

y = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
# Lấy 4, 5, 6
y[1, :]



array([4, 5, 6])

In [ ]:
# Lấy 2, 5
y[:2, 1]

array([2, 5])

In [ ]:
# Lấy 3, 4
np.array([y[0,2], y[1,0]])

array([3, 4])

In [ ]:
# Lấy 9, 6, 3
y[::-1, 2]

array([9, 6, 3])

# BTVN 3

cho x = [1,2,3,4,5,6,7,8,9,10]

1. Xuất ra các giá trị chắn sử dụng if
2. Xuất ra các giá trị chắn sử dụng list comprehension


In [ ]:
#1. Xuất ra các giá trị chắn sử dụng if
x = [1,2,3,4,5,6,7,8,9,10]
for i in x:
    if i % 2 == 0:
        print(i)


2
4
6
8
10


In [ ]:
#2. Xuất ra các giá trị chắn sử dụng list comprehension
even_numbers = [i for i in x if i % 2 == 0]
print(even_numbers)


[2, 4, 6, 8, 10]


In [ ]:
np_x= np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [ ]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
np_x 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
idx= [True,True,True,False,True,True,True,False,True,False]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [ ]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
cond1= np_x % 2 != 0
cond2= np_x  < 5
cond3= np_x > 0

np_x[cond1 & cond2 | cond3]


# BTVN 4 
Tạo một mảng numpy có kích thước 150x5. Giả sử mã này chứa 150 mẫu dữ liệu của sinh viên bao gồm chiều cao, cân nặng, tuổi, lương và điểm trung bình

Tách mảng dựa trên 4 cột đầu tiên thành một biến có tên là x và cột cuối cùng thành y


Tách x thành x_train và x_test trong đó x_train chứa 70% dữ liệu và tách y thành y_trend và y_test, trong đó y_train chứa 70% dữ liệu


Tạo 10 tệp dữ liệu x_train không chồng chéo nhau 

In [3]:
import numpy as np

# Đặt seed để kết quả có thể lặp lại
np.random.seed(42)

# Tạo dữ liệu giả cho 150 sinh viên
# [chiều cao, cân nặng, tuổi, lương, điểm trung bình]
data = np.random.rand(150, 5)

data.shape


(150, 5)

In [4]:
# 4 cột đầu là X
X = data[:, :4]

# Cột cuối là y
y = data[:, 4]

X.shape, y.shape


((150, 4), (150,))

In [5]:
# Số mẫu train
train_size = int(0.7 * len(X))  # 105 mẫu

# Trộn dữ liệu trước khi chia
indices = np.random.permutation(len(X))

X = X[indices]
y = y[indices]

# Chia dữ liệu
X_train = X[:train_size]
X_test  = X[train_size:]

y_train = y[:train_size]
y_test  = y[train_size:]

X_train.shape, X_test.shape


((105, 4), (45, 4))

In [6]:
# Chia X_train thành 10 tập con không chồng chéo
x_train_splits = np.array_split(X_train, 10)

# Kiểm tra kích thước từng tập
for i, split in enumerate(x_train_splits):
    print(f"Tập {i+1}: shape = {split.shape}")


Tập 1: shape = (11, 4)
Tập 2: shape = (11, 4)
Tập 3: shape = (11, 4)
Tập 4: shape = (11, 4)
Tập 5: shape = (11, 4)
Tập 6: shape = (10, 4)
Tập 7: shape = (10, 4)
Tập 8: shape = (10, 4)
Tập 9: shape = (10, 4)
Tập 10: shape = (10, 4)
